server.port=9999

database.hibernate.url=jdbc:mysql://mysql-project.c527m7tldwx5.us-west-1.rds.amazonaws.com:3306/test?useSSL=false&serverTimezone=UTC
database.hibernate.username=root
database.hibernate.password=12345678
database.hibernate.driver=com.mysql.cj.jdbc.Driver
database.hibernate.dialect=org.hibernate.dialect.MySQLDialect
database.hibernate.showsql=true




